# Config file for automatic testing at travis-ci.org

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    packages:
      - pandoc

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt -r requirements_test.txt
  - pip install coveralls tox

script:
  - tox -e py36-django111
  - tox -e py36-django21
  - tox -e py36-django22

after_success:
  - pytest --cov=flexible_reports
  - coveralls
  