# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_reports', '0002_auto_20170823_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='attrs',
            field=models.JSONField(default='{}', verbose_name='HTML attributes'),
        ),
    ]
