# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_reports', '0004_auto_20170823_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='attrs',
            field=models.JSONField(blank=True, null=True, verbose_name='HTML attributes'),
        ),
    ]
