# Generated by Django 4.0.6 on 2022-07-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_reports', '0010_auto_20171026_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportelement',
            options={'ordering': ('position',), 'verbose_name': 'Report element', 'verbose_name_plural': 'Report elements'},
        ),
        migrations.AlterField(
            model_name='column',
            name='attrs',
            field=models.JSONField(blank=True, null=True, verbose_name='HTML attributes'),
        ),
        migrations.AlterField(
            model_name='column',
            name='footer_template',
            field=models.TextField(blank=True, default='{{ value }}', help_text='\n        Template for footer. Used only if "Display totals" is enabled. It is\n        rendered with 3 variables:\n        - *count* -- total count of rows in the table,\n        - *value* -- sum of this column\'s values (or row count if non-numeric),\n        - *error* -- string representation of exception in case an exception\n        occurs during addition of column\'s values.\n\n        So, if the column values are numbers, just use {{ value }}. If you want\n        to output number of rows, just use {{ count }}. ', null=True, verbose_name='Footer template'),
        ),
        migrations.AlterField(
            model_name='column',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='column',
            name='strip_html_on_export',
            field=models.BooleanField(default=True, help_text='Strip HTML tags when exporting to other, non-browser\n        formats, like MS Word or MS Excel. ', verbose_name='Strip HTML on export'),
        ),
        migrations.AlterField(
            model_name='columnorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reportelement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='table',
            name='attrs',
            field=models.JSONField(blank=True, null=True, verbose_name='HTML attributes'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
