# Generated by Django 6.0.4 on 2026-05-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flexible_reports", "0012_add_query_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="sample_context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Example values for template parameters in the query (e.g. {"value": 7}). Used only to validate the query on save.',
                verbose_name="Sample parameters",
            ),
        ),
    ]
