# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTestBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.TextField(default='my test bar')),
            ],
        ),
    ]
