# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        regex="^Column/~create/$",
        view=views.ColumnCreateView.as_view(),
        name='Column_create',
    ),
    url(
        regex="^Column/(?P<pk>\d+)/~delete/$",
        view=views.ColumnDeleteView.as_view(),
        name='Column_delete',
    ),
    url(
        regex="^Column/(?P<pk>\d+)/$",
        view=views.ColumnDetailView.as_view(),
        name='Column_detail',
    ),
    url(
        regex="^Column/(?P<pk>\d+)/~update/$",
        view=views.ColumnUpdateView.as_view(),
        name='Column_update',
    ),
    url(
        regex="^Column/$",
        view=views.ColumnListView.as_view(),
        name='Column_list',
    ),
	url(
        regex="^Table/~create/$",
        view=views.TableCreateView.as_view(),
        name='Table_create',
    ),
    url(
        regex="^Table/(?P<pk>\d+)/~delete/$",
        view=views.TableDeleteView.as_view(),
        name='Table_delete',
    ),
    url(
        regex="^Table/(?P<pk>\d+)/$",
        view=views.TableDetailView.as_view(),
        name='Table_detail',
    ),
    url(
        regex="^Table/(?P<pk>\d+)/~update/$",
        view=views.TableUpdateView.as_view(),
        name='Table_update',
    ),
    url(
        regex="^Table/$",
        view=views.TableListView.as_view(),
        name='Table_list',
    ),
	url(
        regex="^Report/~create/$",
        view=views.ReportCreateView.as_view(),
        name='Report_create',
    ),
    url(
        regex="^Report/(?P<pk>\d+)/~delete/$",
        view=views.ReportDeleteView.as_view(),
        name='Report_delete',
    ),
    url(
        regex="^Report/(?P<pk>\d+)/$",
        view=views.ReportDetailView.as_view(),
        name='Report_detail',
    ),
    url(
        regex="^Report/(?P<pk>\d+)/~update/$",
        view=views.ReportUpdateView.as_view(),
        name='Report_update',
    ),
    url(
        regex="^Report/$",
        view=views.ReportListView.as_view(),
        name='Report_list',
    ),
	url(
        regex="^Collection/~create/$",
        view=views.CollectionCreateView.as_view(),
        name='Collection_create',
    ),
    url(
        regex="^Collection/(?P<pk>\d+)/~delete/$",
        view=views.CollectionDeleteView.as_view(),
        name='Collection_delete',
    ),
    url(
        regex="^Collection/(?P<pk>\d+)/$",
        view=views.CollectionDetailView.as_view(),
        name='Collection_detail',
    ),
    url(
        regex="^Collection/(?P<pk>\d+)/~update/$",
        view=views.CollectionUpdateView.as_view(),
        name='Collection_update',
    ),
    url(
        regex="^Collection/$",
        view=views.CollectionListView.as_view(),
        name='Collection_list',
    ),
	]
